### ISSUE TITLE
Carnival not compatible with Android Studio Hedgehog

### ISSUE THREAD

**Issue by tequilaonelove** [hhru/android-multimodule-plugin#102]
**Android studio version:** 
- Android Studio Hedgehog | 2023.1.1 RC 2
- Build #AI-231.9392.1.2311.10980684, built on October 20, 2023

А планируется ли поддержка и когда?
![image](https://github.com/hhru/android-multimodule-plugin/assets/27417279/6952f472-e499-4b1d-8d90-a8fdd388c236)

**Comment by PStrelchenko** [comment]
Привет @tequilaonelove !
Когда выйдет стабильная версия - попробуем выделить время и поддержать. 

А вы именно Carnival пользуетесь, не Geminio? А что именно в нём вы используете?

**Comment by PStrelchenko** [comment]
Поддержали Android Studio Hedgehog
