### ISSUE TITLE
Как добавить новый оператор ?

### ISSUE THREAD

**Issue by ussernamenikita** [hhru/android-multimodule-plugin#104]
Привет, мне нужен оператор на уровне рецепта, чтобы можно было заменить нижнее подчеркивание на точку. Могу ли я его как-то добавить самостоятельно ?

**Comment by ussernamenikita** [comment]
Аналогичный вопрос, для оператора замены нижнее подчеркивание на тире.

**Comment by PStrelchenko** [comment]
Привет, @ussernamenikita !
Посмотри в сторону [StringRecipeExpressionMapper.kt](https://github.com/hhru/android-multimodule-plugin/blob/master/shared/feature/geminio-sdk/src/main/kotlin/ru/hh/plugins/geminio/sdk/template/mapping/expressions/StringRecipeExpressionMapper.kt#L152-L166)

Там перечислены так называемые `modifiers`, которые уже есть в рецепте. По аналогии можно добавить свой. Только тест дополнительно допиши и можно котрибьютить, будем только рады.
