### ISSUE TITLE
Обновление плагина

### ISSUE THREAD

**Issue by GlebMikhailov** [hhru/android-multimodule-plugin#106]
Добрый вечер, обновите пожалуйста плагин, не могу им воспользоваться

```
Plugin 'Geminio' (version '1.8.0') is not compatible with the current version of the IDE, 
because it requires build 232.* or older but the current build is IU-233.14475.28
```

**Comment by PStrelchenko** [comment]
Привет!
Судя по версии, у вас установлена IntelliJ IDEA Ultimate и её версия выше, чем Android Studio Iguana, которую мы поддержали. Тут есть пара проблем:

- Плагин Geminio пока что сильно зависит от внутреннего API именно Android Studio --> Geminio предназначен для использования именно в рамках Android Studio. Поэтому даже если мы поддержим более высокую версию IDE, не факт, что это подойдёт для IntelliJ IDEA Ultimate. 
- Обычно мы поддерживаем новые версии Android Studio только когда они выходят в стейбл. Это, опять же, связано со связью плагина с внутренним API студии. Чтобы не тратить ресурсы, мы откладываем поддержку превью или бета-версий. 

Что могу порекомендовать: недавно я добавил [небольшую доку](https://github.com/hhru/android-multimodule-plugin/blob/master/docs/geminio/geminio_support_new_android_studio.md) про то, как можно попробовать поддержать новую версию IDE. Можете форкнуть проект и попробовать осуществить поддержку самостоятельно.

**Comment by PStrelchenko** [comment]
Закрываю, давно не было активности.
