### ISSUE TITLE
Android Studio 4.2 

### ISSUE THREAD

**Issue by vladislav-isaev** [hhru/android-multimodule-plugin#22]
Ошибка при установке плагина. Версия студии: 
Android Studio 4.2 Canary 16
Build #AI-202.7660.26.42.6939830, built on October 29, 2020
Runtime version: 11.0.8+0-b944-P17168821 amd64
VM: OpenJDK 64-Bit Server VM by N/A
Linux 4.15.0-126-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 4
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: izhangzhihao.rainbow.brackets, org.intellij.plugins.markdown
Current Desktop: ubuntu:GNOME 
![123123123123](https://user-images.githubusercontent.com/64101440/101362985-dcd14080-38b1-11eb-8a5c-5c8d896ff582.png)

**Comment by PStrelchenko** [comment]
Привет!

В данный момент мы не поддерживаем Android Studio 4.2, но в планах поддержка есть. 
Если поддержка нужна right here, right now, то могу предложить форкнуть репозиторий и сделать поддержку самостоятельно - это не должно быть сложно.

**Comment by fsherstobitov** [comment]
Hi! AS4.2 released today and it says Geminio will be disabled after update. Do you have any plans to update the plugin to support AS4.2?

**Comment by PStrelchenko** [comment]
@fsherstobitov , hi! 
Work in progress --> https://github.com/hhru/android-multimodule-plugin/pull/34

**Comment by PStrelchenko** [comment]
@fsherstobitov , hi! Please, check the new version of Geminio (>= 1.1.6). If you faced with another problems, find time to open new issues, please =)
