### ISSUE TITLE
Geminio. Некорректное поведение при работе с несколькими окнами Android Studio

### ISSUE THREAD

**Issue by yuhnin-m** [hhru/android-multimodule-plugin#26]
Добрый день!

Столкнулся с со следующими ситуациями:

1. Пропадают пункты в меню `New -> MVI Tempate` при открытии другого проекта
2. Если был открыт проект в котором не используется Geminio и мы открываем проект с Geminio шаблонами, то в проекте без шаблонов становится доступно создание шаблонов из проекта с Geminio

**Шаги воспроизведения ситуации №1:**
1. Открываем проект 1 в котором используется плагин Geminio
2. Убеждаемся, что в пункте New есть подменю MVI Tempate
3. В студии в открываем проект 2, где не используются шаблоны и плагин
4. В диалоге выбираем пункт: открыть в новом окне
5. Переключаемся в окно студии с проектом 1

Ожидаемый результат: В проекте 1 в пункте New есть подменю MVI Tempate
Фактический результат: В проекте 1  в пункте New нет подменю MVI Tempate

**Шаги воспроизведения ситуации №2:**

1. Открываем проект 1, где не используются шаблоны и плагин
2. Убеждаемся, что в пункте New нет подменю MVI Tempate
3. Открываем проект 2 в котором используется плагин Geminio
4. В диалоге выбираем пункт: открыть в новом окне
5. Убеждаемся, что в пункте New появилось подменю MVI Tempate
6. Переключаемся в окно студии с проектом 1 

Ожидаемый результат: В проекте 1 в пункте New нет подменю MVI Tempate, а в проекте 2 в пункте New есть подменю MVI Tempate
Фактический результат: Во обоих проектах появился пункт создания шаблона из проекта 2

```
Android Studio 4.1.1
Build #AI-201.8743.12.41.6953283, built on November 5, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.4.0-58-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1998M
Cores: 6
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: com.codertainment.scrcpy, Lombook Plugin, org.jetbrains.kotlin, ru.hh.plugins.Geminio
Current Desktop: KDE
```

**Comment by PStrelchenko** [comment]
Привет!

Спасибо за подробное описание проблемы, постараюсь починить в ближайшее время. Отпишу сюда, когда закончу.
