### ISSUE TITLE
could you give me a demo?

### ISSUE THREAD

**Issue by tang5011235** [hhru/android-multimodule-plugin#27]
i install this plugin , but  i couldn't parse my geminio_config.yaml

**Comment by PStrelchenko** [comment]
Hi!

What kind of demo do you want? 

We have a special [README](https://github.com/hhru/android-multimodule-plugin/blob/master/plugins/hh-geminio/README_EN.md) for you, you can start from there.

**Comment by jiangmw** [comment]
here: [https://github.com/hhru/android-style-guide/tree/master/tools/geminio](url)

**Comment by PStrelchenko** [comment]
Closed because of lack of activity
