### ISSUE TITLE
Some small issues set

### ISSUE THREAD

**Issue by horseunnamed** [hhru/android-multimodule-plugin#28]
## 1) Дублирование итемов в списке New... при переоткрытии проекта
Шаги воспроизведения: 
1. Открыть проект, убедиться, что в пункте меню New... есть шаблоны, каждый из них в единственном экземпляре
2. File -> Close project -> открыть этот же проект еще раз (в реальности бывает нужно при добавлении шаблона, чтобы Geminio его увидел)
3. Снова идем в New... и видим, что каждый итем дублируется. При повторном переоткрытии задублируются еще раз

_Можно  ли добавить кнопку для пересканирования шаблонов проекта без его переоткрытия?_

## 2) Обязетельность поля help для виджетов
Кажется, что избыточно, часто дублируется с достаточно понятным name

## 3) Автосинк после генерации кода по шаблону
Можно ли сделать это опциональным в настройках плагина? Немного мешает при отладке шаблонов.

**Comment by etaskaevhh** [comment]
Все реализовано и поправлено в новой версии 1.2.0
