### ISSUE TITLE
дефолтные значения

### ISSUE THREAD

**Issue by AlexeyKorshun** [hhru/android-multimodule-plugin#37]
в wizard при создании модуля по дефолту ставится пакет от hh. можно вынести в настройки плагина, поля с дефолтным пакетом при создании

**Comment by etaskaevhh** [comment]
@AlexeyKorshun
в текущей версии такая возможность уже есть
посмотри - https://github.com/hhru/android-multimodule-plugin/blob/master/plugins/hh-geminio/docs/ru/recipe_content/PREDEFINED_FEATURES.md
