### ISSUE TITLE
Specified localPath '/Applications/Android Studio.app' doesn't exist or is not a directory

### ISSUE THREAD

**Issue by mrcoder09** [hhru/android-multimodule-plugin#45]
I am trying to build this project in my intellij idea IDE  and getting this error 

Specified localPath '/Applications/Android Studio.app' doesn't exist or is not a directory

There is no way or any solutions I have found yet regarding this. So I am stuck with this error at the very initial step. Please provide solution to resolve this. Also please provide clear list of instructions by including some UI screenshot for building this project.

**Comment by PStrelchenko** [comment]
@mrcoder09 , hi!
Can you try latest version from master branch? I've just merged support for Arctic Fox

**Comment by PStrelchenko** [comment]
Closed due to inactivity.
