### ISSUE TITLE
Как отлаживать?

### ISSUE THREAD

**Issue by iblinov65apps** [hhru/android-multimodule-plugin#55]
При выборе некоторых шаблонов ничего не генерируется. Явно проблема в том, что в рецептах допущены ошибки. 
Попробовал специально добавить ошибку в вычисляемом поле рецепта — модуль перестал генерироваться, даже не показывается окно для ввода данных о модуле. 
Где можно посмотреть, какая именно ошибка произошла? В Event Log пусто. 
Просто смотря на ничем не подсвеченный текст рецептов сложно понять, в чем дело. Хочется увидеть хотя бы что-то похожее на stacktrace ошибки.

IDE:
_Android Studio Arctic Fox | 2020.3.1 Patch 4_

**Comment by iblinov65apps** [comment]
@PStrelchenko @LionZXY может вы сможете подсказать? не понимаю, где смотреть ошибки в AS

**Comment by PStrelchenko** [comment]
@iblinov65apps привет!
Обычно ошибки сваливаются в предупреждения, которые появляются в нижней части Android Studio, рядом с `Event Log`. Записал для тебя небольшой видос, как это выглядит. Должно немного помочь. 

https://user-images.githubusercontent.com/40827829/153183688-2e27a7d7-dda8-4b25-b86c-5607d2ff3339.mov

**Comment by iblinov65apps** [comment]
о, круто)
увидел. спасибо!
