### ISSUE TITLE
Gradle: Build model после использования шаблона

### ISSUE THREAD

**Issue by PaulProject** [hhru/android-multimodule-plugin#60]
Добрый день.

После каждого использования шаблона происходит Gradle: Configure project с последующим Gradle: Build Model. В зависимости от величины проекта ребилд может занимать большое количество времени.
Как можно избавиться от билд грэдл?

Спасибо

**Comment by AlexeyKorshun** [comment]
Привет, вроде нет, его вызывает АПИ студии которое используется для создания шаблона, штатные шаблоны так же вызывают ребилд

**Comment by etaskaevhh** [comment]
В версии 1.2.0, после генерации по шаблону, появился диалог с возможность пропустить синхронизацию
