### ISSUE TITLE
Chipmunk

### ISSUE THREAD

**Issue by iblinov65apps** [hhru/android-multimodule-plugin#63]
Плагин не поддерживается очередной версией студии. Сможете обновить?

![image](https://user-images.githubusercontent.com/36724892/168561867-66fa8a08-3ab8-49b1-9e32-d303c852c2ad.png)

**Comment by LionZXY** [comment]
https://github.com/hhru/android-multimodule-plugin/pull/64
https://github.com/LionZXY/android-multimodule-plugin/releases/tag/build-3

**Comment by iblinov65apps** [comment]
работает. спасибо!
