### ISSUE TITLE
Geminio: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by s097t0r1** [hhru/android-multimodule-plugin#76]
Собрав и установив Geminio, столкнулся со следующей ошибкой: [stacktrace.txt](https://github.com/hhru/android-multimodule-plugin/files/9826491/stacktrace.txt). При попытке зайти в настройки плагина - бесконечная загрузка
![image](https://user-images.githubusercontent.com/47451179/196861351-93fcdb14-78f8-4b62-9776-b814fc4b4372.png)

**Comment by densakh** [comment]
Подключали .jar? Попробуйте .zip подключить, находится в `build/distribuitons`

**Comment by s097t0r1** [comment]
@densakh Спасибо большое! Заработало.
