### ISSUE TITLE
Geminio not compatible with Android Studio Electric Eel

### ISSUE THREAD

**Issue by andreiciubancanWD** [hhru/android-multimodule-plugin#79]
Please update Geminio so it works with Android Studio Electric Eel 

This is the error received when trying to install the latest Geminio version (1.3.0)

![image](https://user-images.githubusercontent.com/55138713/214789798-645e22a5-92ed-4b05-8af5-37b2f24597fc.png)

**Comment by iblinov65apps** [comment]
@PStrelchenko @LionZXY (или кто другой из вашей команды) можете поделиться планами, берете ли это в работу?
как и раньше, новая версия студии отрезает возможность пользоваться вашим плагином

**Comment by PStrelchenko** [comment]
Планируем это взять в работу, где-то через неделю, после текущих задач.

**Comment by iblinov65apps** [comment]
спасибо. будем ждать

**Comment by PStrelchenko** [comment]
Добавили поддержку и [сделали релиз](https://github.com/hhru/android-multimodule-plugin/releases/tag/geminio-1.4.0)

**Comment by iblinov65apps** [comment]
отлично. спасибо!

**Comment by andreiciubancanWD** [comment]
Thank you!
